importar  tortuga
stiven = tortuga . tortuga ()

stiven _ ht ()
stiven _ tamaño del bolígrafo ( 1 )
stiven _ velocidad ( 100 )
stiven _ pu ()
stiven _ posición de ajuste ( - 600 , - 150 )
stiven _ p.d. ()
#Letras
stiven _ comenzar_llenar ()
stiven _ color ( "negro" )
stiven _ correcto ( 90 )
stiven _ adelante ( 75 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 25 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 95 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 25 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 25 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 25 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 25 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 25 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 35 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 25 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 25 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 35 )
stiven _ correcto ( 90 )
stiven _ adelante ( 25 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 35 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 25 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 25 )
stiven _ correcto ( 90 )
stiven _ adelante ( 25 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 45 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 25 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 45 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 25 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 35 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 45 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 25 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 90 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 25 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 25 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 25 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 45 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 25 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 25 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 35 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 35 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 25 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 25 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 55 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 25 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 25 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 55 )
stiven _ correcto ( 90 )
stiven _ adelante ( 15 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 35 )
stiven _ correcto ( 90 )
stiven _ adelante ( 25 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ correcto ( 90 )
stiven _ adelante ( 35 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 15 )
stiven _ end_fill ()
#letras:TIENDA
stiven _ velocidad ( 5 )
stiven _ pu ()
stiven _ posición de ajuste ( - 450 , - 250 )
stiven _ tamaño del bolígrafo ( 3 )
stiven _ p.d. ()
stiven _ penup ()
stiven _ atrás ( 175 )
stiven _ pendown ()
stiven _ correcto ( 90 )
stiven _ adelante ( 140 )
stiven _ correcto ( 90 )
stiven _ adelante ( 50 )
stiven _ atrás ( 100 )
stiven _ penup ()
stiven _ adelante ( 125 )
stiven _ pendown ()
stiven _ adelante ( 100 )
stiven _ atrás ( 50 )
stiven _ correcto ( 90 )
stiven _ adelante ( 140 )
stiven _ correcto ( 90 )
stiven _ adelante ( 50 )
stiven _ atrás ( 100 )
stiven _ penup ()
stiven _ atrás ( 25 )
stiven _ correcto ( 90 )
stiven _ adelante ( 140 )
stiven _ correcto ( 90 )
stiven _ correcto ( 70 )
stiven _ pendown ()
stiven _ adelante ( 148.6606875 )
stiven _ izquierda ( 142 )
stiven _ adelante ( 148.6606875 )
stiven _ correcto ( 72 )
stiven _ penup ()
stiven _ adelante ( 25 )
stiven _ pendown ()
stiven _ adelante ( 100 )
stiven _ atrás ( 100 )
stiven _ correcto ( 90 )
stiven _ adelante ( 70 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 100 )
stiven _ atrás ( 100 )
stiven _ correcto ( 90 )
stiven _ adelante ( 70 )
stiven _ izquierda ( 90 )
stiven _ adelante ( 100 )
stiven _ penup ()
stiven _ adelante ( 25 )
stiven _ izquierda ( 90 )
stiven _ pendown ()
stiven _ adelante ( 140 )
stiven _ correcto ( 90 )
stiven _ correcto ( 45 )
stiven _ adelante ( 198 )
stiven _ izquierda ( 135 )
stiven _ adelante ( 140 )

stiven _ penup ()
stiven _ posición de ajuste ( - 620 , - 270 )
stiven _ pendown ()
stiven _ tamaño del bolígrafo ( 5 )
stiven _ correcto ( 90 )
stiven _ adelante ( 1200 )

stiven _ penup ()
stiven _ posición de ajuste ( - 620 , - 280 )
stiven _ pendown ()
stiven _ adelante ( 800 )

stiven _ velocidad ( 100 )
stiven _ penup ()
stiven _ posición de ajuste ( 450 , - 100 )
stiven _ pendown ()
stiven _ tamaño del bolígrafo ( 1 )
z  =  0
f  =  0
stiven _ velocidad ( 10 )
stiven _ velocidad ( 10000000 )
mientras que  es cierto :
    para  i  en el  rango ( 4 ):
        stiven _ adelante ( 40 )
        stiven _ correcto ( 90 )
    stiven _ correcto ( 15 )
    z  +=  1
    si  z  >=  390 / 15 :
        stiven _ adelante ( 25 )
        z  =  0
        f  +=  1
        si  f  >=  12 :
            descanso

tortuga _ hecho ()